name: supervisor_prof_seeker_03_2025
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain==0.1.16
      - langgraph==0.0.34
      - langsmith
      - openai
      - beautifulsoup4
      - requests
      - unstructured
      - pandas
      - tqdm
      - chromadb
      - instructor
      - pydantic
      - bs4
      - duckduckgo-search
      - sentence-transformers
      - nltk
      - python-dotenv
      - playwright
      - lxml
      - html2text
      - markdownify
      - pypdf
      - PyMuPDF
      - fastapi
      - uvicorn
      - typer
      - rich
      - ipykernel
